apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - list: 
      # The template below uses these parameters
      elements: 
      - cluster: cluster-1
        url: https://kubernetes.default.svc
      - cluster: cluster-2
        url: https://34.57.36.45
  template: 
    # inserts cluster and url values from parameters defined above
    metadata:
      name: '{{cluster}}-myapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/arnabgcp/DemoApp.git
        targetRevision: HEAD
        path: dev/apps
      destination:
        server: '{{url}}'
        namespace: myapp
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-services
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/arnabgcp/DemoApp.git
    targetRevision: HEAD
    path: dev/svc
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true